# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.7'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# コンソールの出力結果を見やすくする Read more: https://rubygems.org/gems/hirb
gem 'hirb', '~> 0.7.3'

# hirbの文字列補正用  Read more: https://rubygems.org/gems/hirb-unicode-steakknife
gem 'hirb-unicode-steakknife', '~> 0.0.9'

# パスワード暗号化用 Read more: https://rubygems.org/gems/bcrypt
gem 'bcrypt', '~> 3.1', '>= 3.1.18'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# jwt Read more:https://rubygems.org/gems/jwt
gem 'jwt', '~> 2.6'

# httpclient Read more: https://rubygems.org/gems/httpclient
gem 'httpclient', '~> 2.8', '>= 2.8.3'

# dotenv Read more: https://rubygems.org/gems/dotenv-rails
gem 'dotenv-rails', '~> 2.8', '>= 2.8.1'
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'faker'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # RuboCop is a Ruby code style checking and code formatting tool. It aims to enforce the community-driven Ruby Style Guide. Read more: https://rubygems.org/gems/rubocop
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'minitest-reporters', '~> 1.1', '>= 1.1.11'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
